### ISSUE TITLE
[24-02-02 유미정] 모달 반응형 미적용, 모바일 버전 모달 위치 수정

### ISSUE THREAD

**Issue by ymj0828** [TickyTocky/TickyTocky#72]
**버그 설명**

1. 모달 두 버전 반응형이 안됩니다.
2. 모달 모바일 크기에서 가로 가운데 정렬이 되지 않습니다.

**재현 방법**

반응형 스타일은 responsive(M) 중괄호 안에 넣어주시면 됩니다.
```jsx
  @include responsive(M) {
    width: 100%;
    margin: 0 1.5rem;
  }
```

**예상 동작**

1. 모바일에서만 width: 100%, margin: 0 1.5rem; 적용
2. 모바일 크기가 되면 양쪽에 margin이 있고 가운데 정렬이 되어야 합니다.

**스크린샷**

![image](https://github.com/TickyTocky/TickyTocky/assets/96277798/8ad50398-dd6d-4273-83f6-ae9011072538)

**Comment by grapefruit13** [comment]
해결된 이슈는 close 바랍니다~
