### ISSUE TITLE
[24-02-03 유미정] Icon Modal 오버레이 배경색 미적용

### ISSUE THREAD

**Issue by ymj0828** [TickyTocky/TickyTocky#74]
**버그 설명**

Common Modal은 오버레이 배경색이 잘 나오는데 Icon Modal은 배경색이 적용이 안됩니다.

**재현 방법**

scss 파일에서 Icon Modal 오버레이에 배경색 적용하기

**스크린샷**

![image](https://github.com/TickyTocky/TickyTocky/assets/96277798/e58f1fde-0d91-40a4-a2a4-be584ed0fe58)

**Comment by grapefruit13** [comment]
시안에서 common modal이랑 icon modal이 겹쳐있을 때, icon modal의 overlay background가 투명해서 컬러를 안 줬던 것인데 줘야할까요?!

**Comment by grapefruit13** [comment]
이 건에 대해서 금일 스크럼에서 얘기 나누었는데요, 오버레이 없는 것 유지하고 추후  box shadow 연하게 바꾸기로 하였습니다!
